.PHONY: all
all: figure2.pdf figure3.pdf figure4.pdf figure5.pdf

figure2.pdf: figure2.py
	python figure2.py

figure3.pdf: figure3.py
	python figure3.py

figure4.pdf figure5.pdf: figure4_and_5.py
	python figure4_and_5.py
