#!/usr/bin/env python

"""
This script reproduces Figures 2-5 in the paper.

The input data is read from the directory `../micromagnetic_simulation_data/reference_data/oommf/`
in this repository. This input data needs to have been previously generated by running the script
`../src/micromagnetic_simulation_scripts/oommf/generate_data.sh`.

The resulting plots are saved to the directory `../figures/generated_from_reference_data/oommf/`.

The input and output directories can be changed using the command line switches `--data-dir` and
`--output-dir`, respectively.

"""

import argparse
import os
import textwrap
import sys

from postprocessing import DataReader, make_figure_2, make_figure_3, make_figure_4, make_figure_5

here = os.path.abspath(os.path.dirname(__file__))


def check_input_data_exists(data_dir):
    """
    Check that all required input files exists and abort if this is not the case.
    """
    filenames = ['dynamic_txyz.txt', 'mxs.npy', 'mys.npy', 'mzs.npy']

    def input_data_file_exists(fname):
        return os.path.exists(os.path.join(data_dir, fname))

    if not all([input_data_file_exists(fname) for fname in filenames]):
        print(textwrap.dedent("""\
            Could not find input data in the following directory:

                {data_dir}

            Please make sure this directory exists and contains the following
            files: {filenames}

            You can use '--data-dir' to specify a different input data directory
            (run 'python reproduce_figures.py --help' for details).
            """.format(data_dir=data_dir, filenames=filenames)))
        sys.exit()


def reproduce_figures(data_dir, output_dir):
    """
    This function reproduces Figures 2-5. It reads the raw simulation
    data from `data_dir` and stores the resulting plots in `output_dir`.

    """
    check_input_data_exists(data_dir)

    # Create output directory if it does not exists
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    print("\nUsing the following data and output directories \n"
          "(run 'python reproduce_figures.py --help' to see \n"
          "how you can change these).\n")

    print("Input data directory:\n   {}\n".format(os.path.abspath(data_dir)))
    print("Output directory:\n   {}\n".format(os.path.abspath(output_dir)))

    # Create DataReader which provides a convenient way of
    # reading raw simulation data and computing derived data.
    data_reader = DataReader(data_dir, data_format='OOMMF')

    print("Generating plots..."),; sys.stdout.flush()

    # Generate plots
    fig2 = make_figure_2(data_reader)
    fig3 = make_figure_3(data_reader)
    fig4 = make_figure_4(data_reader)
    fig5 = make_figure_5(data_reader)

    # Save plots to output directory
    fig2.savefig(os.path.join(output_dir, 'figure_2.png'))
    fig3.savefig(os.path.join(output_dir, 'figure_3.png'))
    fig4.savefig(os.path.join(output_dir, 'figure_4.png'))
    fig5.savefig(os.path.join(output_dir, 'figure_5.png'))

    print("Done.")
    print("Plots have been successfully generated in output directory.")


if __name__ == '__main__':
    default_data_dir = os.path.join(here, '../micromagnetic_simulation_data/recomputed_data/oommf/')
    default_output_dir = os.path.join(here, '../figures/generated_from_reference_data/oommf/')

    parser = argparse.ArgumentParser(description='Reproduce figures 2-5 in the paper.')
    parser.add_argument('--data-dir', dest='data_dir', type=str, default=default_data_dir,
                        help='Directory containing the raw simulation data')
    parser.add_argument('--output-dir', dest='output_dir', type=str, default=default_output_dir,
                        help='Directory where the output plot will be saved')
    args = parser.parse_args()

    reproduce_figures(args.data_dir, args.output_dir)
